"""add uptime_records table

Revision ID: 2237fb926131
Revises: add_translations_table
Create Date: 2026-02-03 19:11:00.539883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2237fb926131'
down_revision: Union[str, None] = 'add_translations_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'translations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_disclaimer_session', table_name='disclaimer_acknowledgments')
    op.create_index(op.f('ix_disclaimer_acknowledgments_id'), 'disclaimer_acknowledgments', ['id'], unique=False)
    op.create_index(op.f('ix_disclaimer_acknowledgments_session_id'), 'disclaimer_acknowledgments', ['session_id'], unique=False)
    op.alter_column('map_layers', 'service_codes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('map_layers', 'routing_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('service_definitions', 'routing_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('service_definitions', 'translations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('service_requests', 'media_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('service_requests', 'flagged',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('service_requests', 'matched_asset',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('service_requests', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_service_requests_manual_priority', table_name='service_requests', postgresql_where='(manual_priority_score IS NOT NULL)')
    op.create_index(op.f('ix_service_requests_archived_at'), 'service_requests', ['archived_at'], unique=False)
    op.create_index(op.f('ix_service_requests_deleted_at'), 'service_requests', ['deleted_at'], unique=False)
    op.drop_column('service_requests', 'matched_polygon')
    op.drop_column('service_requests', 'photos')
    op.drop_column('service_requests', 'media_url')
    op.drop_column('service_requests', 'vertex_ai_priority_score')
    op.alter_column('system_settings', 'township_boundary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('system_settings', 'translations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('system_settings', 'social_links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'notification_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('\'{"sms_urgent_only": false, "email_daily_digest": false, "email_new_comments": true, "sms_new_assignment": false, "email_new_assignment": true, "email_status_changes": true}\'::jsonb'))
    op.drop_constraint('users_auth0_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.create_unique_constraint('users_auth0_id_key', 'users', ['auth0_id'])
    op.alter_column('users', 'notification_preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text('\'{"sms_urgent_only": false, "email_daily_digest": false, "email_new_comments": true, "sms_new_assignment": false, "email_new_assignment": true, "email_status_changes": true}\'::jsonb'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('system_settings', 'social_links',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('system_settings', 'translations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('system_settings', 'township_boundary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('service_requests', sa.Column('vertex_ai_priority_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('matched_polygon', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_service_requests_deleted_at'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_archived_at'), table_name='service_requests')
    op.create_index('idx_service_requests_manual_priority', 'service_requests', ['manual_priority_score'], unique=False, postgresql_where='(manual_priority_score IS NOT NULL)')
    op.alter_column('service_requests', 'custom_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('service_requests', 'matched_asset',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('service_requests', 'flagged',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('service_requests', 'media_urls',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('service_definitions', 'translations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('service_definitions', 'routing_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('map_layers', 'routing_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('map_layers', 'service_codes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_disclaimer_acknowledgments_session_id'), table_name='disclaimer_acknowledgments')
    op.drop_index(op.f('ix_disclaimer_acknowledgments_id'), table_name='disclaimer_acknowledgments')
    op.create_index('idx_disclaimer_session', 'disclaimer_acknowledgments', ['session_id'], unique=False)
    op.alter_column('departments', 'translations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
